---
- hosts: all
  sudo: True
  tasks:
    - name: ensure test user account exists
      mysql_user:
        login_host: 127.0.0.1
        login_user: root
        login_password: "{{ mariadb_mysql_root_password }}"
        name: test
        password: test
        host: localhost
        state: present
