---
- hosts: localhost
  gather_facts: False
  sudo: False
  tasks:

    - name: check out docker role from github.com
      git:
        repo: 'https://github.com/marklee77/ansible-role-docker.git'
        dest: roles/marklee77.docker
        update: yes

    - name: check out roles needed for demo deployment from github.com
      git:
        repo: 'https://github.com/marklee77/ansible-role-mariadb.git'
        dest: roles/marklee77.mariadb
        update: yes
