---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - marklee77.docker
    - { role: marklee77.mariadb, mariadb_bind_address: 0.0.0.0 }

- hosts: all
  gather_facts: False
  sudo: True
  tasks:
    - name: ensure python-keystoneclient module is installed
      apt:
        pkg: python-keystoneclient
        state: latest
        update_cache: yes
        cache_valid_time: 600
