---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - { role: marklee77.docker, when: dockerized_deployment }

- hosts: all
  gather_facts: True
  sudo: True
  tasks:
    - name: ensure python-mysqldb module is pre-installed for dockerized deployment
      apt:
        pkg: python-mysqldb
        state: latest
        update_cache: yes
        cache_valid_time: 600
      when: dockerized_deployment
