---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - marklee77.docker

- hosts: all
  gather_facts: False
  sudo: True
  tasks:
    - name: ensure python-keystoneclient module is installed
      apt:
        pkg: python-keystoneclient
        state: latest
        update_cache: yes
        cache_valid_time: 600
