---
- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - marklee77.docker
    - { role: marklee77.mariadb, mariadb_bind_address: 0.0.0.0 }
    - marklee77.keystone

- hosts: all
  gather_facts: True
  sudo: True
  tasks:

    - name: ensure required packages for prep are installed
      apt:
        pkg: python-mysqldb
        state: latest
        update_cache: yes
        cache_valid_time: 600

