---
- hosts: all
  sudo: True
  tasks:

    - name: ensure packages required for testing are installed
      apt:
        pkg: python-glanceclient
        state: latest
        update_cache: yes
        cache_valid_time: 600
