---
- name: ensure keystone is properly configured
  ini_file:
    dest: /etc/keystone/keystone.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: admin_token,
        value: "{{ keystone_admin_token }}" }
    - { section: DEFAULT, option: log_dir, value: "{{ keystone_log_dir }}" }
    - { section: database, option: connection,
        value: "mysql://keystone:{{ keystone_mysql_keystone_password }}@{{ keystone_mysql_host }}:{{ keystone_mysql_port }}/keystone" }
  notify:
    - restart keystone

- name: update mariadb root password for local root account
  mysql_user: 
    name: root 
    host: localhost 
    password: "{{ mariadb_mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update .my.cnf file with root password credentials
  template: 
    src: root/.my.cnf 
    dest: /root/.my.cnf 
    owner: root 
    group: root 
    mode: 0600

- name: update mariadb root password for all other local root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mariadb_mysql_root_password }}" 
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

