---
- name: ensure dockerfile directories exist
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/.ansible_cache"
    - "{{ ansible_env.HOME }}/.ansible_cache/docker"

#- name: copy role to remote cache for Dockerfile build
#  copy:
#    src: ../
#    dest: "{{ ansible_env.HOME }}/.ansible_cache/docker/mariadb"

- git:
    repo: https://github.com/marklee77/ansible-role-mariadb.git
    dest: "{{ ansible_env.HOME }}/.ansible_cache/docker/mariadb"
    version: dockerized
    update: yes

- name: ensure mariadb docker image has been built
  docker_image:
    name: "{{ mariadb_docker_username }}/mariadb"
    path: "{{ ansible_env.HOME }}/.ansible_cache/docker/mariadb"
    state: present

- name: ensure mariadb data container exists
  docker:
    image: "{{ mariadb_docker_username }}/{{ mariadb_docker_imagename }}"
    name: mariadb_data
    command: /bin/true
    detach: no
    state: present
  notify:
    - set mariadb remote root password

- name: ensure mariadb service is running
  docker:
    image: "{{ mariadb_docker_username }}/{{ mariadb_docker_imagename }}"
    name: mariadb_server
    volumes_from: mariadb_data
    ports: "{% if !mariadb_enable_remote %}127.0.0.1:{% endif %}3306:{{ mariadb_port }}"
    state: running
