---
- name: ensure glance packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-glanceclient
    - python-mysqldb
    - glance

- name: ensure glance is started and enabled for direct deployments
  service: 
    name: glance
    state: started 
    enabled: yes
  when: not glance_dockerized_deployment

- name: ensure glance is properly shut down for dockerized deployments
  service:
    name: glance
    state: stopped
    enabled: yes
 
