---
- name: ensure neutron controller packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - python-mysqldb
    - python-neutronclient

- name: ensure that neutron directories exist and have correct permissions
  file:
    path: "{{ item }}"
    owner: neutron
    group: neutron
    mode: 0700
    state: directory
  with_items:
    - /etc/neutron
    - /var/lib/neutron
    - /var/run/neutron
    - /var/lock/neutron
    - /var/log/neutron

- name: ensure supervisor is installed for dockerized deployments 
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - supervisor

- name: update supervisor configuration from template for dockerized deployments
  template:
    src: etc/supervisor/conf.d/supervisord.conf
    dest: /etc/supervisor/conf.d/supervisord.conf
    owner: root
    group: root
    mode: 0644

- name: ensure neutron controller is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - neutron-server

- name: ensure neutron controller is properly shut down for dockerized deployments
  service:
    name: "{{ item }}"
    state: stopped
    enabled: yes
  with_items:
    - neutron-server
  when: neutron_controller_dockerize_context is defined
