---
- name: ensure neutron controller packages and dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - neutron-server
    - neutron-plugin-ml2
    - python-mysqldb
    - python-neutronclient

- name: ensure neutron controller is started and enabled
  service: 
    name: "{{ item }}"
    state: started 
    enabled: yes
  with_items:
    - neutron-server
