---
- name: ensure mariadb dependency packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-software-properties

- name: ensure mariadb repository public key is installed
  register: apt_key
  command: apt-key adv --recv-key --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  changed_when: apt_key.stderr.find("imported") != -1

- name: ensure mariadb repository is enabled
  apt_repository: 
    repo: deb {{ mariadb_repository_mirror }}/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main
    update_cache: yes
    state: present

- name: ensure mariadb packages and ansible dependencies are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - mariadb-server
    - mariadb-client
    - python-mysqldb

- name: ensure mariadb is started and enabled
  service: 
    name: mysql
    state: started 
    enabled: yes

- name: update mariadb root password for local root account
  mysql_user: 
    name: root 
    host: localhost 
    password: "{{ mariadb_root_mysql_password }}"
    priv: "*.*:ALL,GRANT"
    state: present

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update .my.cnf file with root password credentials
  template: 
    src: root/.my.cnf 
    dest: /root/.my.cnf 
    owner: root 
    group: root 
    mode: 0600

- name: update mariadb root password for all other root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mariadb_root_mysql_password }}" 
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: 
    name: "" 
    host: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_hostname }}"
    - "{{ inventory_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1
    - "%"

