---
- include: prep.yml
  when: glance_dockerize_context is not defined

- include: docker.yml
  when: glance_dockerized_deployment

- include: install.yml
  when: not glance_dockerized_deployment and (
        glance_dockerize_context is not defined or
        glance_dockerize_context == "install" )

- include: offline_configuration.yml
  when: not glance_dockerized_deployment and (
        glance_dockerize_context is not defined or
        glance_dockerize_context == "offline_configuration" )

- include: online_configuration.yml
  when: not glance_dockerized_deployment and (
        glance_dockerize_context is not defined or
        glance_dockerize_context == "online_configuration" )
