---
- include: mysql.yml

- include: rabbitmq.yml

- include: docker.yml
  when: neutron_controller_dockerized_deployment

- include: install.yml
  when: not neutron_controller_dockerized_deployment 

- include: offline_configuration.yml
  when: not neutron_controller_dockerized_deployment 

- include: keystone.yml
