---
# FIXME: for security we assume root login requires direct login access to mysql
# node, needs delegate_to for non-centralized deployments.

- name: ensure neutron database is present
  mysql_db:
    login_host: 127.0.0.1
    login_port: "{{ openstack_mysql_port }}"
    login_user: root
    login_password: "{{ openstack_mysql_root_password }}"
    name: neutron
  register: create_neutron_db

- name: ensure neutron database user is present
  mysql_user:
    login_host: 127.0.0.1
    login_port: "{{ openstack_mysql_port }}"
    login_user: root
    login_password: "{{ openstack_mysql_root_password }}"
    name: neutron
    host: "{{ item }}"
    password: "{{ openstack_mysql_neutron_password }}"
    priv: neutron.*:ALL
  with_items:
    - localhost
    - "%"
