---
- name: ensure neutron database is present
  mysql_db:
    login_host: "{{ neutron_mysql_host }}"
    login_port: "{{ neutron_mysql_port }}"
    login_user: root
    login_password: "{{ neutron_mysql_root_password }}"
    name: neutron
  register: create_neutron_db

- name: ensure neutron database user is present
  mysql_user:
    login_host: "{{ neutron_mysql_host }}"
    login_port: "{{ neutron_mysql_port }}"
    login_user: root
    login_password: "{{ neutron_mysql_root_password }}"
    name: neutron
    host: "{{ item }}"
    password: "{{ neutron_mysql_neutron_password }}"
    priv: neutron.*:ALL
  with_items:
    - localhost
    - "%"
