---
- name: ensure glance is properly configured
  ini_file:
    dest: /etc/glance/glance.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: DEFAULT, option: verbose, value: "{{ glance_log_verbose }}" }
    - { section: DEFAULT, option: debug, value: "{{ glance_log_debug }}" }
    - { section: DEFAULT, option: log_dir, value: "{{ glance_log_dir }}" }
    - { section: database, option: connection,
        value: "mysql://glance:{{ glance_mysql_glance_password }}@{{ 
                  glance_mysql_host }}:{{ glance_mysql_port }}/glance" }
  register: modify_glance_ini

- name: ensure glance sqlite is deleted
  file:
    dest: /var/lib/glance/glance.sqlite
    state: absent

- name: ensure database is synced
  command: /usr/bin/glance-manage db_sync 
  when: glance_dockerize_context is defined or
        create_glance_db|changed

- name: restart glance
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - glance-registry
    - glance-api
  when: modify_glance_ini|changed and
        glance_dockerize_context is not defined
