---
- name: wait until glance service is ready
  wait_for:
    delay: 1
    host: "{{ glance_endpoint_host }}"
    port: glance
    state: started

- name: add glance user to the service tenant with the admin role
  keystone_user:
    endpoint: "{{ glance_keystone_admin_url }}"
    token: "{{ glance_keystone_admin_token }}"
    tenant: service
    user: glance
    role: admin

- name: add glance endpoint
  keystone_service:
    endpoint: "{{ glance_keystone_admin_url }}"
    token: "{{ glance_keystone_admin_token }}"
    region: "{{ glance_keystone_region }}"
    name: glance
    type: image
    description: "Image Service"
    public_url: "{{ glance_public_url }}"
    internal_url: "{{ glance_internal_url }}"
    admin_url: "{{ glance_admin_url }}"

