---
- name: ensure glance database is present
  mysql_db:
    name: glance
  register: create_glance_db

- name: ensure glance database user is present
  mysql_user:
    name: glance
    host: "{{ item }}"
    password: "{{ glance_mysql_glance_password }}"
    priv: glance.*:ALL
  with_items:
    - localhost
    - "%"

- name: create glance user in keystone
  keystone_user:
    endpoint: "{{ keystone_admin_url }}"
    token: "{{ keystone_admin_token }}"
    tenant: service
    user: glance
    password: "{{ glance_identity_password }}"

