---
- name: restart keystone
  service: 
    name: keystone
    state: restarted
  when: not keystone_dockerized_deploy and
        keystone_dockerize_context is not defined

- name: perform keystone docker online configuration
  docker:
    image: "{{ keystone_docker_username }}/{{ keystone_docker_imagename }}"
    name: "{{ keystone_docker_containername }}_configure"
    volumes_from: "{{ keystone_docker_containername }}_data"
    detach: no
    command: >
              ansible-playbook -i inventories/local.ini deploy.yml -e '{
                "keystone_dockerize_context" : "online_configuration",
                "keystone_mysql_root_password" : 
                  "{{ keystone_mysql_root_password }}",
                "keystone_mysql_keystone_password" : 
                  "{{ keystone_mysql_keystone_password }}" }'
    state: present

