---
- name: perform keystone docker online configuration
  docker:
    image: "{{ keystone_docker_username }}/{{ keystone_docker_imagename }}"
    name: "{{ keystone_docker_containername }}_configure"
    volumes_from: "{{ keystone_docker_containername }}_data"
    detach: no
    command: >
              ansible-playbook -i inventories/local.ini deploy.yml -e '{
                "keystone_dockerize_context" : "online_configuration",
                "keystone_endpoint_host" :
                  "{{ ansible_docker0['ipv4']['address'] }}",
                "keystone_admin_token" : "{{ keystone_admin_token }}",
                "keystone_keystone_admin_password" : 
                  "{{ keystone_keystone_admin_password }}" }'
    state: present
