---
- hosts: localhost
  gather_facts: False
  sudo: False
  tasks:

    - name: check out docker role from github.com
      git:
        repo: 'https://github.com/marklee77/ansible-role-docker.git'
        dest: roles/marklee77.docker
        update: yes
      when: dockerized_deployment


- hosts: all
  gather_facts: True
  sudo: True
  roles:
    - { role: marklee77.docker, when: dockerized_deployment }
